# Build Openwrt docker-compose
#
services:
  build_openwrt:
    image: build_openwrt:v1.0
    container_name: build_openwrt
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - ROOT_PASSWD=whoami
      - MY_USER=whoami
      - MY_USER_PASSWD=whoami
      - ALL_PROXY=
      - http_proxy=
      - https_proxy=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./
        target: /home/whoami/work
    network_mode: host
    stdin_open: true
    tty: true

